version: "3"
services:
  node-app:
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=olsi
      - MONGO_PASSWORD=olsi
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=olsi
      - MONGO_INITDB_ROOT_PASSWORD=olsi
